databases:
  - name: driver
    plan: free
    databaseName: driver
    user: driver_user

services:
  - type: web
    plan: free
    name: driver_app
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: driver
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false